services:
  database:
    image: postgres:17
    restart: always
    shm_size: 128mb
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_USER=local_user
      - POSTGRES_DB=playground_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: