services:
  database:
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_USER=local_user
      - POSTGRES_DB=local_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: